apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24tbWluLTMyLWNoYXJzLWxvbmc=
  DATABASE_URL: cG9zdGdyZXNxbDovL2Nsb3VkY29tbWVyY2U6Y2xvdWRjb21tZXJjZUBwb3N0Z3Jlcy5pbmZyYS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2Nsb3VkY29tbWVyY2U=
---
apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
  namespace: product
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24tbWluLTMyLWNoYXJzLWxvbmc=
  MONGODB_URI: bW9uZ29kYjovL21vbmdvLmluZnJhLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2Nsb3VkY29tbWVyY2U=
---
apiVersion: v1
kind: Secret
metadata:
  name: cart-secrets
  namespace: cart
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24tbWluLTMyLWNoYXJzLWxvbmc=
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  namespace: order
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24tbWluLTMyLWNoYXJzLWxvbmc=
  DATABASE_URL: cG9zdGdyZXNxbDovL2Nsb3VkY29tbWVyY2U6Y2xvdWRjb21tZXJjZUBwb3N0Z3Jlcy5pbmZyYS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2Nsb3VkY29tbWVyY2U=
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: payment
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2Nsb3VkY29tbWVyY2U6Y2xvdWRjb21tZXJjZUBwb3N0Z3Jlcy5pbmZyYS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2Nsb3VkY29tbWVyY2U=
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: frontend
type: Opaque
data:
  VITE_API_URL: aHR0cDovL2F1dGguY2xvdWRjb21tZXJjZS5sb2NhbA==